name: Execute Hlasovani notebook

on: [push]

jobs:
  run-notebooks:
    name: Run Jupyter notebooks for Snemovna
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v1
        with:
          activate-environment: snemovna
          environment-file: environment.yml
          python-version: 3.7
      - name: Run Hlasovani
        run: jupyter nbconvert --to notebook --execute Hlasovani.ipynb
    #- uses: actions/upload-artifact@master
    #  if: always()
    #  with:
    #    name: output
    #    path: ${{ RUNNER.temp }}/nb-runner
    #  env:
    #    RUNNER: ${{ toJson(runner) }}
