name: Execute Hlasovani notebook

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Hlasovani
      uses: Hybrid-Performance-Method/interval@v1
      with:
        notebook: Hlasovani.ipynb
        #output: s3://notebooks/output.ipynb
        hasDate: "false"
        #parameters: parameters.yml
        #requirements: "package1==1.0.0 package2==1.1.0"
        #secret: ${{ secret.MY_SECRETS }}
    #- uses: actions/upload-artifact@master
    #  if: always()
    #  with:
    #    name: output
    #    path: ${{ RUNNER.temp }}/nb-runner
    #  env:
    #    RUNNER: ${{ toJson(runner) }}
