name: Execute Hlasovani notebook

on: [push]

jobs:
  run-notebooks:
    name: Run Jupyter notebooks for Snemovna
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create venv and install requirements
        run: python3 -m venv venv && source venv/bin/activate && pip install -r requirements.txt
      - name: Run Hlasovani
        run: source venv/bin/activate && jupyter nbconvert --to notebook --execute Hlasovani.ipynb
    #- uses: actions/upload-artifact@master
    #  if: always()
    #  with:
    #    name: output
    #    path: ${{ RUNNER.temp }}/nb-runner
    #  env:
    #    RUNNER: ${{ toJson(runner) }}
